/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.android.factory;

import android.app.Activity;
import android.view.View;
import android.hardware.SensorEventListener;
import android.widget.TextView;
import android.widget.Button;
import android.hardware.Sensor;
import android.hardware.SensorManager;
import android.os.IPowerManager;
import android.content.Intent;
import android.os.Bundle;
import android.view.Window;
import android.os.ServiceManager;
import android.os.IBinder;
import android.hardware.SensorEvent;
import android.util.Log;
import android.content.res.Resources;
import android.view.MotionEvent;

public class SensorTest extends Activity implements SensorEventListener {
    TextView AlsPs_Light;
    TextView AlsPs_Proxi;
    TextView Gsensor_X;
    TextView Gsensor_Y;
    TextView Gsensor_Z;
    private Sensor mALSSensor;
    private Sensor mGSensor;
    private Sensor mPSSensor;
    private SensorManager mSensorManager;
    Thread mThread;
    IPowerManager server;
    TextView textView3;
    TextView tv_AL;
    TextView tv_AL_result;
    TextView tv_AP_result;
    TextView tv_G_XR;
    TextView tv_G_XR1;
    TextView tv_G_YR;
    TextView tv_G_YR1;
    TextView tv_G_ZR;
    TextView tv_G_ZR1;
    TextView tv_G_result;
    static int SensorTestStatus = 0x0;
    //starmen set 3 direction begin
    TextView tv_G_X1_text;
	TextView tv_G_Y1_text;
	TextView tv_G_Z1_text;
    //starmen set 3 direction end
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.sensor_test_nops);
        getWindow().addFlags(0x80);
        mSensorManager = (SensorManager)getSystemService("sensor");
        mGSensor = mSensorManager.getDefaultSensor(0x1);
        mALSSensor = mSensorManager.getDefaultSensor(0x5);
        mPSSensor = mSensorManager.getDefaultSensor(0x8);
        server = IPowerManager.Stub.asInterface(ServiceManager.getService("power"));

        Gsensor_X = (TextView)findViewById(R.id.Gsensor_X);
        Gsensor_Y = (TextView)findViewById(R.id.Gsensor_Y);
        Gsensor_Z = (TextView)findViewById(R.id.Gsensor_Z);
        tv_G_XR = (TextView)findViewById(R.id.tv_G_XR);
        tv_G_XR1 = (TextView)findViewById(R.id.tv_G_XR1);
        tv_G_YR = (TextView)findViewById(R.id.tv_G_YR);
        tv_G_YR1 = (TextView)findViewById(R.id.tv_G_YR1);
        tv_G_ZR = (TextView)findViewById(R.id.tv_G_ZR);
        tv_G_ZR1 = (TextView)findViewById(R.id.tv_G_ZR1);
        tv_AL = (TextView)findViewById(R.id.tv_AL);
        AlsPs_Light = (TextView)findViewById(R.id.AlsPs_Light);
        textView3 = (TextView)findViewById(R.id.textView3);
        tv_G_result = (TextView)findViewById(R.id.tv_G_result);
        tv_AL_result = (TextView)findViewById(R.id.tv_AL_result);
        tv_AL.setVisibility(0x4);
        AlsPs_Light.setVisibility(0x4);
        textView3.setVisibility(0x4);
        if(mGSensor != null) {
            mSensorManager.registerListener(this, mGSensor, 0x3);
        }
        if(mALSSensor != null) {
            mSensorManager.registerListener(this, mALSSensor, 0x3);
        }
        if(mPSSensor != null) {
            mSensorManager.registerListener(this, mPSSensor, 0x3);
        }
		//starmen set 3 direction begin
		tv_G_X1_text=(TextView)findViewById(R.id.tv_G_X1);
		tv_G_X1_text.setVisibility(View.INVISIBLE);
		tv_G_Y1_text=(TextView)findViewById(R.id.tv_G_Y1);
		tv_G_Y1_text.setVisibility(View.INVISIBLE);
		tv_G_Z1_text=(TextView)findViewById(R.id.tv_G_Z1);
		tv_G_Z1_text.setVisibility(View.INVISIBLE);
        tv_G_XR1.setVisibility(View.INVISIBLE);
        tv_G_YR1.setVisibility(View.INVISIBLE);
        tv_G_ZR1.setVisibility(View.INVISIBLE);
		//starmen set 3 direction end
    }
    
    protected void onDestroy() {
        mSensorManager.unregisterListener(this);
        super.onDestroy();
    }
    
    public void onSensorChanged(SensorEvent event) {
        if(event.sensor.getType() == 0x1) {
            Gsensor_X.setText("X values is   " + event.values[0x0] + "");
            Gsensor_Y.setText("Y values is   " + event.values[0x1] + "");
            Gsensor_Z.setText("Z values is   " + event.values[0x2] + "");
			 //starmen set 3 direction begin
			/*
            if(((int)event.values[0x0] == 0x9) && ((int)event.values[0x1] == 0) && ((int)event.values[0x2] == 0)) {
                tv_G_XR.setText("OK");
                tv_G_XR.setTextColor(-0xff0100);
            }
            if(((int)event.values[0x0] == -0x9) && ((int)event.values[0x1] == 0) && ((int)event.values[0x2] == 0)) {
                tv_G_XR1.setText("OK");
                tv_G_XR1.setTextColor(-0xff0100);
            }
            if(((int)event.values[0x0] == 0) && ((int)event.values[0x1] == 0x9) && ((int)event.values[0x2] == 0)) {
                tv_G_YR.setText("OK");
                tv_G_YR.setTextColor(-0xff0100);
            }
            if(((int)event.values[0x0] == 0) && ((int)event.values[0x1] == -0x9) && ((int)event.values[0x2] == 0)) {
                tv_G_YR1.setText("OK");
                tv_G_YR1.setTextColor(-0xff0100);
            }
            if(((int)event.values[0x0] == 0) && ((int)event.values[0x1] == 0) && ((int)event.values[0x2] == 0x9)) {
                tv_G_ZR.setText("OK");
                tv_G_ZR.setTextColor(-0xff0100);
            }
            if(((int)event.values[0x0] == 0) && ((int)event.values[0x1] == 0) && ((int)event.values[0x2] == -0x9)) {
                tv_G_ZR1.setText("OK");
                tv_G_ZR1.setTextColor(-0xff0100);
            }
            */
            if((((int)event.values[0x0] == 0x9) && ((int)event.values[0x1] == 0) && ((int)event.values[0x2] == 0))||
				(((int)event.values[0x0] == -0x9) && ((int)event.values[0x1] == 0) && ((int)event.values[0x2] == 0))){
                tv_G_XR.setText("OK");
                tv_G_XR.setTextColor(-0xff0100);
            }
			if((((int)event.values[0x0] == 0) && ((int)event.values[0x1] == 0x9) && ((int)event.values[0x2] == 0))||
				(((int)event.values[0x0] == 0) && ((int)event.values[0x1] == -0x9) && ((int)event.values[0x2] == 0))){
                tv_G_YR.setText("OK");
                tv_G_YR.setTextColor(-0xff0100);
            }
			if((((int)event.values[0x0] == 0) && ((int)event.values[0x1] == 0) && ((int)event.values[0x2] == 0x9))||
				(((int)event.values[0x0] == 0) && ((int)event.values[0x1] == 0) && ((int)event.values[0x2] == -0x9))){
                tv_G_ZR.setText("OK");
                tv_G_ZR.setTextColor(-0xff0100);
            }
			//starmen set 3 direction end
            if(("OK".equals(tv_G_XR.getText())) || ("OK".equals(tv_G_XR1.getText())) || ("OK".equals(tv_G_YR.getText())) || ("OK".equals(tv_G_YR1.getText())) || ("OK".equals(tv_G_ZR.getText())) || ("OK".equals(tv_G_ZR1.getText()))) {
                tv_G_result.setText(R.string.Button_Status_Success);
                tv_G_result.setTextColor(-0xff0100);
               
            } else {
                tv_G_result.setText(R.string.Button_Status_Fail);
                tv_G_result.setTextColor(0xffff0000);
            }
        }
        if(event.sensor.getType() == 0x5) {
            AlsPs_Light.setText(" values is   " + event.values[0x0] + "");
        }
        if(event.sensor.getType() == 0x8) {
            Log.e("lyaotao", "event.values[0] = " + event.values[0x0]);
            try {
                if("0.0".equals("" + event.values[0x0])) {
                    AlsPs_Light.setText(getResources().getString(R.string.Text_ALSPS_VALUE_CLOSE) + "");
                    return;
                }
                AlsPs_Light.setText(getResources().getString(R.string.Text_ALSPS_VALUE_AWAY) + "");
                return;
            } catch(Exception e) {
                Log.e("lyaotao", "333");
            }
        }
    }
    
    public boolean onTouchEvent(MotionEvent event) {
        if((event.getY() > 0x0) && (event.getY() < 200.0f)) {
            Log.e("lyaotao", "event.getY = " + event.getY());
            mSensorManager.registerListener(this, mPSSensor, 0x3);
        }
        return super.onTouchEvent(event);
    }
    
    public void onAccuracyChanged(Sensor sensor, int accuracy) {
    }
}
